final List<String> currencyCodes = [
  'EUR - Euro',
  'GBP - British Pound Sterling',
  'CHF - Swiss Franc',
  'NOK - Norwegian Krone',
  'SEK - Swedish Krona',
  'DKK - Danish Krone',
  'CZK - Czech Koruna',
  'PLN - Polish Złoty',
  'HUF - Hungarian Forint',
  'RUB - Russian Ruble',
  'BGN - Bulgarian Lev',
  'HRK - Croatian Kuna',
  'RON - Romanian Leu',
  'LTL - Lithuanian Litas',
  'EEK - Estonian Kroon',
  'SIT - Slovenian Tolar',
  'CYP - Cypriot Pound',
  'MKD - Macedonian Denar',
  'IEP - Irish Punt (discontinued in 2002)',
  'BEF - Belgian Franc (discontinued in 2002)'
];
